<?php
// region-bundles.php
// Return a mapping of region name => [ 'price' => float, 'councils' => [ 'Council A', 'Council B', ... ] ]

function pis_get_region_bundles() {
    return [
        'Buckinghamshire Councils' => [
            'price' => 11,
            'councils' => [
                'Aylesbury Vale', 'Chiltern and South Bucks', 'Slough', 'Wycombe'
            ],
        ],
        'East and South East London Councils' => [
            'price' => 28,
            'councils' => [
                'Barking and Dagenham','Bexley','Bromley','Croydon','Greenwich','Hackney',
                'Havering','Lewisham','Newham','Redbridge','Southwark','Tower Hamlets','Waltham Forest'
            ],
        ],
        'East London Councils' => [
            'price' => 16,
            'councils' => [
                'Barking and Dagenham',
                'Hackney',
                'Havering',
                'Newham',
                'Redbridge',
                'Tower Hamlets',
                'Waltham Forest'
            ],
        ],
        'East Midlands Region Councils' => [
            'price' => 72,
            'councils' => [
                'Amber Valley', 'Ashfield', 'Bassetlaw', 'Blaby', 'Bolsover',
                'Boston', 'Broxtowe', 'Charnwood', 'Chesterfield', 'Corby', 
                'West Northamptonshire', 'Derby', 'Derbyshire Dales', 'East Lindsey',
                'East Northamptonshire', 'Erewash', 'Gedling', 'Harborough', 'High Peak',
                'Hinckley and Bosworth', 'Kettering', 'Leicester', 'Lincoln',
                'Mansfield', 'Melton', 'Newark and Sherwood', 'North East Derbyshire',
                'North Kesteven', 'North West Leicestershire' ,'Nottingham', 'Oadby and Wigston', 'Rushcliffe',
                'Rutland', 'South Derbyshire', 'South Holland', 'South Kesteven','Wellingborough', 'West Lindsey'
            ],
        ],
        'East of England Region Councils' => [
            'price' => 79,
            'councils' => [
                'Babergh and Mid Suffolk', 'Basildon', 'Bedford', 'Braintree', 'Breckland', 'Brentwood',
                'Broxbourne', 'Cambridge' , 'Cambridgeshire', 'Castle Point', 'Central Bedfordshire', 'Chelmsford',
                'Colchester', 'Dacorum', 'East Cambridgeshire', 'East Hertfordshire', 'East Suffolk',
                'Epping Forest', 'Fenland', 'Great Yarmouth', 'Harlow', 'Hertsmere',
                'Huntingdonshire', 'Ipswich', 'King’s Lynn and West Norfolk',
                'Luton', 'Maldon', 'North Hertfordshire', 'Norht Norfolk', 'Norwich', 'Peterborough', 'Rochford', 'South Norfolk',
                'Southend-on-Sea', 'St Albans', 'Stevenage', 'Tendring', 'Three Rivers', 'Thurrock',
                'Uttlesford', 'Watford', 'Welwyn Hatfield', 'West Suffolk'
            ],
        ],
        'East Sussex Councils' => [
            'price' => 12,
            'councils' => [
                'Crawley',
                'Hastings',
                'Lewes and Eastbourne',
                'Rother',
                'Wealden'
            ],
        ],
        'Hampshire Councils' => [
            'price' => 22,
            'councils' => [
                'Basingstoke and Deane',
                'Chichester',
                'East Hampshire',
                'Eastleigh',
                'Gosport',
                'Hart',
                'Havant',
                'Portsmouth',
                'Southampton',
                'Test Valley',
                'Winchester'
            ],
        ],
        'Kent Councils' => [
            'price' => 21,
            'councils' => [
                'Ashford',
                'Canterbury',
                'Dartford',
                'Dover',
                'Gravesham',
                'Maidstone & Swale',
                'Sevenoaks',
                'Thanet',
                'Tonbridge and Malling',
                'Tunbridge Wells'
            ],
        ],
        'London Region Councils' => [
            'price' => 59,
            'councils' => [
                'Barking and Dagenham',
                'Barnet',
                'Bexley',
                'Brent',
                'Bromley',
                'Camden',
                'City of London',
                'Croydon',
                'Ealing',
                'Enfield',
                'Greenwich',
                'Hackney',
                'Hammersmith & Fulham',
                'Haringey',
                'Harrow',
                'Havering',
                'Hillingdon',
                'Hounslow',
                'Islington',
                'Kensington and Chelsea',
                'Kingston upon Thames',
                'Lambeth',
                'Lewisham',
                'Merton',
                'Newham',
                'Redbridge',
                'Richmond upon Thames',
                'Southwark',
                'Sutton',
                'Tower Hamlets',
                'Waltham Forest',
                'Wandsworth',
                'Westminster'
            ],
        ],
        'North and West London Councils' => [
            'price' => 29,
            'councils' => [
                'Barnet',
                'Brent',
                'Camden',
                'City of London',
                'Ealing',
                'Enfield',
                'Hammersmith & Fulham',
                'Haringey',
                'Harrow',
                'Hillingdon',
                'Hounslow',
                'Islington',
                'Kensington and Chelsea',
                'Westminster'
            ],
        ],
        'North East Region Councils' => [
            'price' => 20,
            'councils' => [
                'Darlington',
                'Durham',
                'Gateshead',
                'Middlesbrough',
                'Newcastle upon Tyne',
                'North Tyneside',
                'Northumberland',
                'Redcar and Cleveland',
                'South Tyneside',
                'Stockton on Tees',
                'Sunderland'
            ],
        ],
        'North London Councils' => [
            'price' => 15,
            'councils' => [
                'Barnet',
                'Camden',
                'City of London',
                'Enfield',
                'Haringey',
                'Islington',
                'Westminster'
            ],
        ],
        'Northwest Region Councils' => [
            'price' => 71,
            'councils' => [
                'Allerdale',
                'Barrow in Furness',
                'Blackburn with Darwen',
                'Blackpool',
                'Bolton',
                'Burnley',
                'Bury',
                'Carlisle',
                'Cheshire East',
                'Cheshire West and Chester',
                'Chorley',
                'Copeland',
                'Fylde',
                'Halton',
                'Knowsley',
                'Lancaster',
                'Liverpool',
                'Manchester',
                'Oldham',
                'Pendle',
                'Preston',
                'Ribble Valley',
                'Rochdale',
                'Rossendale',
                'Salford',
                'Sefton',
                'South Ribble',
                'St Helens',
                'Stockport',
                'Tameside',
                'Trafford',
                'Warrington',
                'West Lancashire',
                'Westmorland & Furness',
                'Wigan',
                'Wirral',
                'Wyre'
            ],
        ],
        'Oxfordshire Councils' => [
            'price' => 11,
            'councils' => [
                'Cherwell',
                'Oxford',
                'South Oxfordshire',
                'Vale of White Horse',
                'West Oxfordshire'
            ],
        ],
        'Reading' => [
            'price' => 15,
            'councils' => [
                'Basingstoke and Deane',
                'Reading',
                'Runnymede',
                'South Oxfordshire',
                'West Berkshire',
                'Windsor and Maidenhead',
                'Wokingham'
            ],
        ],
        'Scotland Region Councils' => [
            'price' => 52,
            'councils' => [
                'Aberdeen City',
                'Aberdeenshire',
                'Angus',
                'Argyll and Bute',
                'Clackmannanshire',
                'Dumfries and Galloway',
                'East Ayrshire',
                'East Dunbartonshire',
                'East Lothian',
                'East Renfrewshire',
                'Edinburgh',
                'Falkirk',
                'Fife',
                'Glasgow',
                'Highland',
                'Inverclyde',
                'Midlothian',
                'Moray',
                'North Ayrshire',
                'North Lanarkshire',
                'Orkney Islands',
                'Perth and Kinross',
                'Renfrewshire',
                'Scottish Borders',
                'Shetland Islands',
                'South Ayrshire',
                'Stirling',
                'West Dunbartonshire',
                'West Lothian'
            ],
        ],
        'South East London Councils' => [
            'price' => 13,
            'councils' => [
                'Bexley',
                'Bromley',
                'Croydon',
                'Greenwich',
                'Lewisham',
                'Southwark'
            ],
        ],
        'South East Region Councils' => [
            'price' => 98,
            'councils' => [
                'Adur and Worthing',
                'Arun',
                'Ashford',
                'Aylesbury Vale',
                'Basingstoke and Deane',
                'Bracknell Forest',
                'Brighton and Hove',
                'Canterbury',
                'Cherwell',
                'Chichester',
                'Chiltern and South Bucks',
                'Crawley',
                'Dartford',
                'Dover',
                'East Hampshire',
                'Eastleigh',
                'Elmbridge',
                'Epsom and Ewell',
                'Fareham',
                'Folkestone and Hythe',
                'Gosport',
                'Gravesham',
                'Guildford',
                'Hart',
                'Hastings',
                'Havant',
                'Horsham',
                'Isle of Wight',
                'Lewes and Eastbourne',
                'Maidstone & Swale',
                'Medway',
                'Mid Sussex',
                'Milton Keynes',
                'Mole Valley',
                'New Forest',
                'Oxford',
                'Portsmouth',
                'Reading',
                'Reigate and Banstead',
                'Rother',
                'Runnymede',
                'Rushmoor',
                'Sevenoaks',
                'Slough',
                'South Oxfordshire',
                'Southampton',
                'Spelthorne',
                'Surrey Heath',
                'Tandridge',
                'Test Valley',
                'Thanet',
                'Tonbridge and Malling',
                'Tunbridge Wells',
                'Vale of White Horse',
                'Waverly',
                'Wealden',
                'West Berkshire',
                'West Oxfordshire',
                'Winchester',
                'Windsor and Maidenhead',
                'Woking',
                'Wokingham',
                'Wycombe'
            ],
        ],
        'South West and South East London Councils' => [
            'price' => 25,
            'councils' => [
                'Bexley',
                'Bromley',
                'Croydon',
                'Greenwich',
                'Kingston upon Thames',
                'Lambeth',
                'Lewisham',
                'Merton',
                'Richmond upon Thames',
                'Southwark',
                'Sutton',
                'Wandsworth'
            ],
        ],
        'South West London Councils' => [
            'price' => 13,
            'councils' => [
                'Kingston upon Thames',
                'Lambeth',
                'Merton',
                'Richmond upon Thames',
                'Sutton',
                'Wandsworth'
            ],
        ],
        'South West Region Councils' => [
            'price' => 56,
            'councils' => [
                'Bath and North East Somerset',
                'Bournemouth',
                'Christchurch & Poole',
                'Bristol',
                'Cheltenham',
                'Cornwall',
                'Cotswold',
                'East / North / West Dorset',
                'Purbeck',
                'Weymouth and Portland',
                'East Devon',
                'Exeter',
                'Forest of Dean',
                'Isles of Scilly',
                'Mendip',
                'Mid Devon',
                'North Devon',
                'North Somerset',
                'Plymouth',
                'Sedgemoor',
                'Somerset West',
                'South Gloucestershire',
                'South Hams and West Devon',
                'South Somerset',
                'Stroud',
                'Swindon',
                'Teignbridge',
                'Tewkesbury',
                'Torbay',
                'Torridge',
                'Wiltshire'
            ],
        ],
        'Surrey Councils' => [
            'price' => 24,
            'councils' => [
                'Elmbridge',
                'Epsom and Ewell',
                'Guildford',
                'Mole Valley',
                'Reigate and Banstead',
                'Runnymede',
                'Rushmore',
                'Spelthorne',
                'Surrey Heath',
                'Tandridge',
                'Waverly',
                'Woking'
            ],
        ],
        'Wales Region Councils' => [
            'price' => 41,
            'councils' => [
                'Blaenau Gwent',
                'Bridgend',
                'Caerphilly',
                'Cardiff',
                'Carmarthenshire',
                'Ceredigion',
                'Conwy',
                'Denbighshire',
                'Flintshire',
                'Gwynedd',
                'Isle of Anglesey',
                'Merthyr Tydfil',
                'Monmouthshire',
                'Neath Port Talbot',
                'Newport',
                'Pembrokeshire',
                'Powys',
                'Rhondda Cynon Taf',
                'Swansea',
                'Torfaen',
                'Vale of Glamorgan',
                'Wrexham'
            ],
        ],
        'West London Councils' => [
            'price' => 15,
            'councils' => [
                'Brent',
                'Ealing',
                'Hammersmith & Fulham',
                'Harrow',
                'Hillingdon',
                'Hounslow',
                'Kensington and Chelsea'
            ],
        ],
        'West Midlands Region Councils' => [
            'price' => 51,
            'councils' => [
                'Birmingham',
                'Bromsgrove and Redditch',
                'Cannock Chase',
                'Coventry',
                'Dudley',
                'East Staffordshire',
                'Herefordshire',
                'Lichfield',
                'Malvern Hills',
                'Newcastle under Lyme',
                'North Warwickshire',
                'Nuneaton and Bedworth',
                'Rugby',
                'Sandwell',
                'Shropshire',
                'Solihull',
                'South Staffordshire',
                'Stafford',
                'Staffordshire Moorlands',
                'Stoke on Trent',
                'Stratford-on-Avon',
                'Tamworth',
                'Telford & Wrekin',
                'Walsall',
                'Warwick',
                'Wolverhampton',
                'Wyre Forest'
            ],
        ],
        'West Sussex Councils' => [
            'price' => 9,
            'councils' => [
                'Adur and Worthing',
                'Arun',
                'Crawley',
                'Horsham'
            ],
        ],
        'Yorkshire & Humber Region Councils' => [
            'price' => 39,
            'councils' => [
                'Barnsley',
                'Bradford',
                'Calderdale',
                'Craven',
                'Doncaster',
                'East Riding of Yorkshire',
                'Hambleton',
                'Harrogate',
                'Hull',
                'Kirklees',
                'Leeds',
                'North East Lincolnshire',
                'North Lincolnshire',
                'Richmondshire',
                'Rotherham',
                'Ryedale',
                'Scarborough',
                'Selby',
                'Sheffield',
                'Wakefield',
                'York'
            ],
        ],
    ];
}
