<?php
/**
 * Planning Index Sync Handler
 * Usage:
 *   wp planning-index-sync import /path/to/apps.db
 */

if ( defined( 'WP_CLI' ) && WP_CLI ) {

    class Planning_Index_Sync_Command {

        /**
         * Import from a local SQLite apps.db
         *
         * ## OPTIONS
         *
         * <db_path>
         * : Path to the SQLite apps.db file generated by scraper.
         */
        public function import( $args, $assoc_args ) {
            list( $db_path ) = $args;

            if ( ! file_exists( $db_path ) ) {
                WP_CLI::error( "Database not found at: $db_path" );
            }

            // open sqlite via PDO
            $pdo = new PDO("sqlite:$db_path");
            $rows = $pdo->query("SELECT * FROM apps_to_sync;")->fetchAll(PDO::FETCH_ASSOC);

            $count = 0;
            foreach ( $rows as $row ) {
                $authority = sanitize_text_field( $row['authority_name'] );
                $ref = sanitize_text_field( $row['council_reference'] );
                $description = sanitize_text_field( $row['description'] );
                $address = sanitize_text_field( $row['address'] );
                $title = substr( $description, 0, 100 );
                // Store only description in post_content (no address concatenation)
                $body = wp_kses_post( $description );

                // Try to find existing post by council_reference
                $existing = get_posts([
                    'post_type' => 'planning_app',
                    'meta_key' => 'council_reference',
                    'meta_value' => $ref,
                    'posts_per_page' => 1,
                ]);

                if ( $existing ) {
                    $post_id = $existing[0]->ID;
                    wp_update_post([
                        'ID' => $post_id,
                        'post_title' => $title,
                        'post_content' => $body,
                    ]);
                } else {
                    $post_id = wp_insert_post([
                        'post_type' => 'planning_app',
                        'post_status' => 'publish',
                        'post_title' => $title,
                        'post_content' => $body,
                    ]);
                }

                if ( ! is_wp_error( $post_id ) ) {
                    wp_set_post_terms( $post_id, [ $authority ], 'authority', false );
                    update_post_meta( $post_id, 'council_reference', $ref );
                    update_post_meta( $post_id, 'description', $description );
                    update_post_meta( $post_id, 'address', $address );
                    update_post_meta( $post_id, 'info_url', $row['info_url'] );
                    update_post_meta( $post_id, 'date_received', $row['date_received'] );
                    update_post_meta( $post_id, 'date_validated', $row['date_validated'] );
                    update_post_meta( $post_id, 'status', $row['status'] );
                    update_post_meta( $post_id, 'decision', $row['decision'] );
                    update_post_meta( $post_id, 'documents_url', $row['documents_url'] );
                    update_post_meta( $post_id, 'last_seen', current_time( 'mysql' ) );
                    update_post_meta( $post_id, 'synced_by', 'CLI' );
                    $count++;
                }
            }

            WP_CLI::success( "Imported or updated $count planning applications." );
        }
    }

    WP_CLI::add_command( 'planning-index-sync', 'Planning_Index_Sync_Command' );
}
